### ISSUE TITLE
Pick a tool to migrate to static page generator

### ISSUE THREAD

**Issue by ku-ya** [fdcl-gwu/WWW#2]
Migrate all the site to use a static page generator for easier maintenance and updates.

**Comment by skulumani** [comment]
Some options include:

* [Jekyll](https://jekyllrb.com/)
* [Hugo](https://gohugo.io/)
* [Pelican](https://www.staticgen.com/pelican)
* [Big list of generators](https://www.staticgen.com/)

We can use [Netlify](https://www.netlify.com/docs/continuous-deployment/) to automatically build and deploy the site

**Comment by tylee-fdcl** [comment]
More than 2 years after the request, I tried Hugo for a few hours, only to find that it is a bit difficult to change the contents of a chosen template, unless I put some efforts to learn about the structures of Hugo. Quickly switched back to editing css directly.
